name: Preview Release

on:
  push:
    branches: [fork]

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - run: pnpm run build
      - run: pnpm dlx pkg-pr-new publish --pnpm './packages/vinext' --no-compact
